allow HDF5_VOL_CONNECTOR set before make check/ptest
Exception: when netcdf4 is used, cache and async VOLs are disabled,
due to errors coming from those VOLs.